
name: Build Zappy AI APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Create Flutter project skeleton
        run: flutter create .
      - name: Restore pubspec & lib
        run: |
          rm -rf lib pubspec.yaml
          cp -R ${{ github.workspace }}/lib ${{ github.workspace }}/
          cp ${{ github.workspace }}/pubspec.yaml ${{ github.workspace }}/
      - name: Install deps & build
        run: |
          flutter pub get
          flutter build apk --release
      - uses: actions/upload-artifact@v4
        with:
          name: zappy_ai_apk
          path: build/app/outputs/flutter-apk/app-release.apk
